
--- @alias errPeripheral
--- | "local peripheral unreachable"
--- | "remote peripheral unreachable"
---
--- @class InventoryComponentUnlimited
--- @field name string peripheral name
--- @field type string
--- @field new fun(p_name: string): InventoryComponentUnlimited
--- @field checkType fun(p_name: string): boolean
--- @field getItems fun(self: table): table<itemName, itemCount>,  errPeripheral | nil
