--- @alias itemName string
--- @alias itemCount number
--- @alias storedItems table<itemName, itemCount>
---
--- @alias storageUnitName
--- |'"minecraft:chest"'
---
--- @class itemDetails
--- @field displayName string
--- @field maxCount number
--- @field weight number
---
--- @class StorageConfig
--- @field peripherals storageUnitName[]
--- also policy, but later
---
---
--- @class storageManager: EventEmitter
--- @field storageUnits table<storageUnitName, storageAdapter>
--- @field sharedItemDetails table<itemName, itemDetails>
--- @field items table<itemName, itemCount>
--- @field itemLocations table<storageUnitName, storedItems>
--- @field updateLock boolean
--- @field updating boolean
--- @field locatePeripherals fun(self: table)
--- @field start fun(self: table)
--- @field runStorageCheck fun(self: table)
--- @field fullScan fun(self: table)
--- @field totalsDiffer fun(self: table, with: table): boolean
--- @field signalChange fun(self: table)
