--- @alias slotIndex number
--- @alias items table<slotIndex, slotInfo> Items we have in possession @alias moved number amount of items moved during an operation
--- @alias cachedDetials table<itemName, itemDetails>
---
--- @class slotInfo
--- @field name itemName
--- @field count itemCount
---
--- @alias integrationModName
--- | '"unlimited"'
--- | '"advanced"'
---
--- @alias adapterStorage table<storageUnitName, storageAdapter>
--- @alias modAdapterStorage table<integrationModName, adapterStorage>
---
---
--- @class slot
--- @field chestIndex number
--- @field itemCount number
---
---
--- @class storageAdapter
--- @field cachedDetails cachedDetials
--- @field name string
--- @field totalCapacity number
--- @field currentCapacity number
--- @field items table<itemName, itemCount>
--- @field new fun(chestName: string, sharedCachedDetails: cachedDetials): storageAdapter | nil
--- @field update fun(self: table): nil | errMessageStorageAdapter
--- @field getItems fun(self: table): items, nil | errMessageStorageAdapter
--- @field pushItem fun(self: table, to: string, itemName: string, itemCount: number): moved, nil | errMessageStorageAdapter
--- @field pullItem fun(self: table, from: string, itemName: string, itemCount: number)
--- @field getCapacity fun(self: table)
--- @field getCapacityForItem fun(self: table, itemName: string)
--- @field transactionMove fun(self: table, to: string, itemName: string, itemCount: number)
--- @field transactionPull fun(self: table, from: string, itemName: string, itemCount: number)
---
---
--- @class chestAdapter: storageAdapter
--- @field getSlot fun(self: table, itemName: itemName): slot
--- @field filledSlots table<itemName, slot[]>
--- @field partiallyFilledSlots table<itemName, Deque>
---
--- @class drawerAdapter: storageAdapter
--- @field storedItemName itemName
--- @field storedItemCount itemCount
--- @field numSlots number
--- @field singleSlotCapacity number
--- @field setup fun(self: table): nil | errMessageStorageAdapter
--- @field inventory InventoryComponentUnlimited
